[package]
name = "filio"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
env_logger = "0.11.3"
log = "0.4.21"
notify = "6.1.1"
serde = "1.0.201"
serde_derive = "1.0.201"
serde_json = "1.0.117"
